version: '3'
networks: 
  HLF:
    external: true 

services: 
  orderer: 
    container_name: orderer 
    image: hyperledger/fabric-orderer:xox-v1
    deploy:
      placement: 
        constraints:
        - node.hostname==heming-rdma14
    environment: 
      - GOPATH=/opt/gopath
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LEDGERTYPE=ram
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: sh -c "mkdir -p /var/hyperledger/production/orderer && orderer start"
    volumes: 
      - /home/yunpeng/hlf_xox_env/channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - /home/yunpeng/hlf_xox_env/organizations/ordererOrganizations/example.com/orderers/xox_orderer.example.com/msp:/var/hyperledger/orderer/msp
      - /home/yunpeng/hlf_xox_env/core.yaml:/etc/hyperledger/fabric/core.yaml
      - /home/yunpeng/hlf_xox_env/orderer.yaml:/etc/hyperledger/fabric/orderer.yaml
      # - /home/yunpeng/benchmark-orderer:/var/hyperledger/production/orderer # ramdisk
    networks:
      - HLF
  fastpeer: 
    container_name: fastpeer
    image: hyperledger/fabric-peer:xox-v1
    deploy: 
      placement:
        constraints:
          - node.hostname==heming-rdma16
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: sh -c "mkdir -p /var/hyperledger/production && peer node start --storageAddr xox_storagepeer:10000"
    environment:
      - GOPATH=/opt/gopath
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=HLF
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_ID=xox_fastpeer
      - CORE_PEER_ADDRESS=xox_fastpeer:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=xox_fastpeer:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=xox_fastpeer:7051
      - CORE_PEER_CHAINCODEADDRESS=xox_fastpeer:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_USELEADERELECTION=false
      - CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_MSGCONFIGPATH=/etc/hyperledger/fabric/msp
    volumes:
      - /var/run/:/host/var/run/
      - /home/yunpeng/hlf_xox_env/organizations/peerOrganizations/org1.example.com/peers/xox_fastpeer.org1.example.com/msp:/etc/hyperledger/fabric/msp
      - /home/yunpeng/hlf_xox_env/chaincode:/opt/gopath/src/github.com/hyperledger/fabric/chaincode
      - /home/yunpeng/hlf_xox_env/core.yaml:/etc/hyperledger/fabric/core.yaml
      - /home/yunpeng/hlf_xox_env/orderer.yaml:/etc/hyperledger/fabric/orderer.yaml
      # - /home/yunpeng/benchmark-fastpeer:/var/hyperledger/production # ramdisk
    networks:
      - HLF

  storagepeer: 
    container_name: storagepeer
    image: hyperledger/fabric-peer:xox-v1
    deploy: 
      placement:
        constraints:
          - node.hostname==heming-rdma17
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: sh -c "mkdir -p /var/hyperledger/production && peer node start -s --storageAddr 0.0.0.0:10000"
    environment:
      - GOPATH=/opt/gopath
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=HLF
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_ID=xox_storagepeer
      - CORE_PEER_ADDRESS=xox_storagepeer:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=xox_fastpeer:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=xox_storagepeer:7051
      - CORE_PEER_CHAINCODEADDRESS=xox_storagepeer:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_USELEADERELECTION=false
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_MSGCONFIGPATH=/etc/hyperledger/fabric/msp
    volumes:
      - /var/run/:/host/var/run/
      - /home/yunpeng/hlf_xox_env/organizations/peerOrganizations/org1.example.com/peers/xox_storagepeer.org1.example.com/msp:/etc/hyperledger/fabric/msp
      - /home/yunpeng/hlf_xox_env/chaincode:/opt/gopath/src/github.com/hyperledger/fabric/chaincode
      - /home/yunpeng/hlf_xox_env/core.yaml:/etc/hyperledger/fabric/core.yaml
      - /home/yunpeng/hlf_xox_env/orderer.yaml:/etc/hyperledger/fabric/orderer.yaml
      # - /home/yunpeng/benchmark-storagepeer:/var/hyperledger/production # ramdisk
    networks:
      - HLF
  peer0:
    container_name: peer0
    image: hyperledger/fabric-peer:xox-v1
    deploy: 
      placement:
        constraints:
          - node.hostname==heming-rdma18
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: sh -c "mkdir -p /var/hyperledger/production && peer node start -e --storageAddr xox_storagepeer:10000"
    environment:
      - GOPATH=/opt/gopath
      - FABRIC_LOGGING_SPEC=INFO 
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=HLF
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_ID=xox_peer0
      - CORE_PEER_ADDRESS=xox_peer0:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=xox_fastpeer:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=xox_peer0:7051
      - CORE_PEER_CHAINCODEADDRESS=xox_peer0:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_USELEADERELECTION=false
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_MSGCONFIGPATH=/etc/hyperledger/fabric/msp
    volumes:
      - /var/run/:/host/var/run/
      - /home/yunpeng/hlf_xox_env/organizations/peerOrganizations/org1.example.com/peers/xox_peer0.org1.example.com/msp:/etc/hyperledger/fabric/msp
      - /home/yunpeng/hlf_xox_env/chaincode:/opt/gopath/src/github.com/hyperledger/fabric/chaincode
      - /home/yunpeng/hlf_xox_env/core.yaml:/etc/hyperledger/fabric/core.yaml
      - /home/yunpeng/hlf_xox_env/orderer.yaml:/etc/hyperledger/fabric/orderer.yaml
      # - /home/yunpeng/benchmark-peer0:/var/hyperledger/production # ramdisk
    networks:
      - HLF
  peer1:
    container_name: peer1
    image: hyperledger/fabric-peer:xox-v1
    deploy: 
      placement:
        constraints:
          - node.hostname==heming-rdma18
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: sh -c "mkdir -p /var/hyperledger/production && peer node start -e --storageAddr xox_storagepeer:10000"
    environment:
      - FABRIC_LOGGING_SPEC=INFO 
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=HLF
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_ID=xox_peer1
      - CORE_PEER_ADDRESS=xox_peer1:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=xox_fastpeer:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=xox_peer1:7051
      - CORE_PEER_CHAINCODEADDRESS=xox_peer1:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_USELEADERELECTION=false
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_MSGCONFIGPATH=/etc/hyperledger/fabric/msp
    volumes:
      - /var/run/:/host/var/run/
      - /home/yunpeng/hlf_xox_env/organizations/peerOrganizations/org1.example.com/peers/xox_peer1.org1.example.com/msp:/etc/hyperledger/fabric/msp
      - /home/yunpeng/hlf_xox_env/chaincode:/opt/gopath/src/github.com/hyperledger/fabric/chaincode
      - /home/yunpeng/hlf_xox_env/core.yaml:/etc/hyperledger/fabric/core.yaml
      - /home/yunpeng/hlf_xox_env/orderer.yaml:/etc/hyperledger/fabric/orderer.yaml
      # - /home/yunpeng/benchmark-peer1:/var/hyperledger/production # ramdisk
    networks:
      - HLF
  peer2:
    container_name: peer2
    image: hyperledger/fabric-peer:xox-v1
    deploy: 
      placement:
        constraints:
          - node.hostname==heming-rdma19
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: sh -c "mkdir -p /var/hyperledger/production && peer node start -e --storageAddr xox_storagepeer:10000"
    environment:
      - FABRIC_LOGGING_SPEC=INFO 
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=HLF
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_ID=xox_peer2
      - CORE_PEER_ADDRESS=xox_peer2:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=xox_fastpeer:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=xox_peer2:7051
      - CORE_PEER_CHAINCODEADDRESS=xox_peer2:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_USELEADERELECTION=false
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_MSGCONFIGPATH=/etc/hyperledger/fabric/msp
    volumes:
      - /var/run/:/host/var/run/
      - /home/yunpeng/hlf_xox_env/organizations/peerOrganizations/org1.example.com/peers/xox_peer2.org1.example.com/msp:/etc/hyperledger/fabric/msp
      - /home/yunpeng/hlf_xox_env/chaincode:/opt/gopath/src/github.com/hyperledger/fabric/chaincode
      - /home/yunpeng/hlf_xox_env/core.yaml:/etc/hyperledger/fabric/core.yaml
      - /home/yunpeng/hlf_xox_env/orderer.yaml:/etc/hyperledger/fabric/orderer.yaml
      # - /home/yunpeng/benchmark-peer2:/var/hyperledger/production # ramdisk
    networks:
      - HLF
  peer3:
    container_name: peer3
    image: hyperledger/fabric-peer:xox-v1
    deploy: 
      placement:
        constraints:
          - node.hostname==heming-rdma19
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: sh -c "mkdir -p /var/hyperledger/production && peer node start -e --storageAddr xox_storagepeer:10000"
    environment:
      - FABRIC_LOGGING_SPEC=INFO 
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=HLF
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_ID=xox_peer3
      - CORE_PEER_ADDRESS=xox_peer3:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=xox_fastpeer:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=xox_peer3:7051
      - CORE_PEER_CHAINCODEADDRESS=xox_peer3:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_USELEADERELECTION=false
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_MSGCONFIGPATH=/etc/hyperledger/fabric/msp
    volumes:
      - /var/run/:/host/var/run/
      - /home/yunpeng/hlf_xox_env/organizations/peerOrganizations/org1.example.com/peers/xox_peer3.org1.example.com/msp:/etc/hyperledger/fabric/msp
      - /home/yunpeng/hlf_xox_env/chaincode:/opt/gopath/src/github.com/hyperledger/fabric/chaincode
      - /home/yunpeng/hlf_xox_env/core.yaml:/etc/hyperledger/fabric/core.yaml
      - /home/yunpeng/hlf_xox_env/orderer.yaml:/etc/hyperledger/fabric/orderer.yaml
      # - /home/yunpeng/benchmark-peer3:/var/hyperledger/production # ramdisk
    networks:
      - HLF
  cli:
    command: /bin/bash
    container_name: cli
    deploy:
      placement:
        constraints:
        - node.hostname==heming-rdma6
    environment:
    - GOPATH=/opt/gopath
    - FABRIC_LOGGING_SPEC=INFO
    - CORE_PEER_ID=cli
    - CORE_PEER_ADDRESS=0.0.0.0:7051
    - CORE_PEER_LOCALMSPID=Org1MSP
    - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
    image: hyperledger/fabric-tools:xox-v1
    networks:
    - HLF
    stdin_open: true
    tty: true
    volumes:
    - /var/run/:/host/var/run/
    - /home/yunpeng/hlf_xox_env/chaincode:/opt/gopath/src/github.com/chaincode
    - /home/yunpeng/hlf_xox_env/organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
    - /home/yunpeng/hlf_xox_env/scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts
    - /home/yunpeng/hlf_xox_env/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    - /home/yunpeng/hlf_xox_env/chaincode:/opt/gopath/src/github.com/hyperledger/fabric/chaincode
    - /home/yunpeng/hlf_xox_env/core.yaml:/etc/hyperledger/fabric/core.yaml
    - /home/yunpeng/hlf_xox_env/orderer.yaml:/etc/hyperledger/fabric/orderer.yaml
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    depends_on:
    - peer0
    - peer1
    - peer2
    - peer3
    - fastpeer
    - storagepeer
    - orderer
  tape:
    container_name: tape
    image: tape:latest
    deploy:
      placement:
        constraints:
        - node.hostname==heming-rdma6
    networks:
    - HLF
    stdin_open: true
    tty: true
    working_dir: /
    command: /bin/sh 
    volumes: 
    - /home/yunpeng/hlf_xox_env/tape.yaml:/config.yaml
    - /home/yunpeng/hlf_xox_env/organizations:/organizations
