#!/bin/bash
source base_parameters.sh

export FABRIC_LOGGING_SPEC=INFO
export ORDERER_GENERAL_LOCALMSPDIR=${FABRIC_CFG_PATH}/crypto-config/ordererOrganizations/${ORDERER_DOMAIN}/orderers/${ORDERER_ADDRESS}.${ORDERER_DOMAIN}/msp
export ORDERER_OPERATIONS_VALIDATORADDRESS=${VALIDATION_ADDRESS}:11000

export ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
export ORDERER_GENERAL_GENESISMETHOD=file
export ORDERER_GENERAL_LEDGERTYPE=ram
export ORDERER_GENERAL_GENESISFILE="${FABRIC_CFG_PATH}"/channel-artifacts/genesis.block
export ORDERER_GENERAL_LOCALMSPID=OrdererMSP

(cd "${FABRIC_ROOT}" && make orderer)
orderer start


